version: '3'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: seventy_developer
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: seventy_development
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      # WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      # WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - .:/var/app/seventy
    depends_on:
      - web
    ports:
      - 3035:3035

  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/app/seventy
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    # pryを使用してデバッグができるよう設定
    tty: true
    stdin_open: true

volumes:
  mysql-volume:
  bundle:
